In [3]:
import pandas as pd
import numpy as np

df = pd.read_csv("/content/data.csv")

In [4]:
df.head()

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1
1        60  '2020/12/02'    117       145     479.0
2        60  '2020/12/03'    103       135     340.0
3        45  '2020/12/04'    109       175     282.4
4        45  '2020/12/05'    117       148     406.0

In [5]:
df.shape
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  32 non-null     int64
 1   Date      31 non-null     object
 2   Pulse     32 non-null     int64
 3   Maxpulse  32 non-null     int64
 4   Calories  30 non-null     float64
dtypes: float64(1), int64(3), object(1)
memory usage: 1.4+ KB

In [6]:
df.isnull().sum()

Duration    0
Date        1
Pulse       0
Maxpulse    0
Calories    2
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(1)

In [9]:
df = df.drop_duplicates()
df.duplicated().sum()

np.int64(0)

In [18]:
df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
df.dtypes

Duration             int64
Date        datetime64[ns]
Pulse                int64
Maxpulse             int64
Calories           float64
dtype: object

In [20]:
df["Year"] = df["Date"].dt.year.astype("Int64")
df[["Date", "Year"]].head()

        Date  Year
0 2020-12-01  2020
1 2020-12-02  2020
2 2020-12-03  2020
3 2020-12-04  2020
4 2020-12-05  2020

In [22]:
df["Heart_Rate_Range"] = df["Maxpulse"] - df["Pulse"]
df[["Pulse", "Maxpulse", "Heart_Rate_Range"]].head()

   Pulse  Maxpulse  Heart_Rate_Range
0    110       130                20
1    117       145                28
2    103       135                32
3    109       175                66
4    117       148                31

In [24]:
df["Intensity"] = pd.cut(
    df["Pulse"],
    bins=[0, 99, 129, 159, float("inf")],
    labels=["Low", "Moderate", "High", "Very High"]
)
df[["Pulse", "Intensity"]].head(10)
df["Intensity"].value_counts()

Intensity
Moderate     23
Low           7
High          1
Very High     0
Name: count, dtype: int64

In [25]:
df["Calories_per_Minute"] = df["Calories"] / df["Duration"]
df[["Duration", "Calories", "Calories_per_Minute"]].head()

   Duration  Calories  Calories_per_Minute
0        60     409.1             6.818333
1        60     479.0             7.983333
2        60     340.0             5.666667
3        45     282.4             6.275556
4        45     406.0             9.022222

In [26]:
df["Workout_Level"] = pd.cut(
    df["Calories"],
    bins=[0, 300, 500, 700, float("inf")],
    labels=["Low", "Moderate", "High", "Very High"]
)
df[["Calories", "Workout_Level"]].head(10)

   Calories Workout_Level
0     409.1      Moderate
1     479.0      Moderate
2     340.0      Moderate
3     282.4           Low
4     406.0      Moderate
5     300.0           Low
6     374.0      Moderate
7     253.3           Low
8     195.1           Low
9     269.0           Low

In [27]:
numeric_columns = df.select_dtypes(include="number").columns

numeric_columns
for column in numeric_columns:
    df[column] = df[column].fillna(df[column].median())
df.isnull().sum()

Duration               0
Date                   1
Pulse                  0
Maxpulse               0
Calories               0
Year                   0
Month                  0
Heart_Rate_Range       0
Intensity              0
Calories_per_Minute    0
Workout_Level          0
dtype: int64

In [28]:
print("Mean:", df["Calories"].mean())
print("Median:", df["Calories"].median())
print("Mode:", df["Calories"].mode()[0])
print("Variance:", df["Calories"].var())

Mean: 306.1193548387096
Median: 300.0
Mode: 300.0
Variance: 4113.473612903227

In [29]:
df.head()

,Duration,Date,Pulse,Maxpulse,Calories,Year,Month,Heart_Rate_Range,Intensity,Calories_per_Minute,Workout_Level
0,60,2020-12-01,110,130,409.1,2020,12.0,20,Moderate,6.818333,Moderate
1,60,2020-12-02,117,145,479.0,2020,12.0,28,Moderate,7.983333,Moderate
2,60,2020-12-03,103,135,340.0,2020,12.0,32,Moderate,5.666667,Moderate
3,45,2020-12-04,109,175,282.4,2020,12.0,66,Moderate,6.275556,Low
4,45,2020-12-05,117,148,406.0,2020,12.0,31,Moderate,9.022222,Moderate

In [30]:
df.columns

Index(['Duration', 'Date', 'Pulse', 'Maxpulse', 'Calories', 'Year', 'Month',
       'Heart_Rate_Range', 'Intensity', 'Calories_per_Minute',
       'Workout_Level'],
      dtype='object')